/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.self.indy.cli;

import org.junit.Test;
import static org.junit.Assert.*;

public class VcxCliTest {
    @Test public void testVcxCli() {
        VcxCli classUnderTest = new VcxCli();
    }
}
