appenders:
  # An appender named "stdout" that writes to stdout
  stdout:
    kind: console
    encoder:
      pattern: '{T}:{l:>5}|{d(%Y-%m-%dT%H:%M:%S%.3f%z):<30}|{f:>35}:{L:<4}| {m}{n}'

  file:
    kind: rolling_file
    path: '/var/log/vcx-cli/libvcx.log'
    encoder:
      pattern: '{T}:{l:>5}|{d(%Y-%m-%dT%H:%M:%S%.3f%z):<30}|{f:>35}:{L:<4}| {m}{n}'
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 100 mb
      roller:
        kind: fixed_window
        pattern: '/var/log/vcx-cli/libvcx{{}}.log'
        base: 1
        count: 10

# Set the default logging level to "warn" and attach the "stdout" appender to the root
root:
  level: trace
  appenders:
    - stdout
    - file
